


#ReqModules
OpenCLABC

#ExpOtp
OpenCLABC.ProgramCode
OpenCLABC.ProgramCodeProperties
TEST
==============================



__kernel void TEST() { }



==============================
True 
True 
OpenCLABC.ProgramCode
OpenCLABC.ProgramCodeProperties
TEST
==============================



__kernel void TEST() { }



==============================
[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#DelegateCount
6


