


#DelegateCount
5

#ExpOtp
OpenCLABC.ProgramCode 
OpenCLABC.ProgramCodeProperties 
k
============================== 
kernel void k() {} 
============================== 
True 
True 
OpenCLABC.ProgramCode 
OpenCLABC.ProgramCodeProperties 
k
============================== 
kernel void k() {} 
============================== 
[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


