


#DelegateCount
5

#ExpOtp
CommandQueueThenQuickConvert<integer,integer,SimpleFuncContainer<integer,integer>,TBooleanTrueFlag>#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	function lambda(i: integer): integer
[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


