


#ReqModules

#ExpOtp
CommandQueueTryFinally<System.Int32>#0
	CommandQueueHostQuickFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostQuickFunc<System.Int32>#1: Int32 <>lambda*()

CommandQueueHandleWithoutRes#0
	CommandQueueHostQuickFunc<System.Int32>#1: Int32 <>lambda*()
	Boolean <>lambda*(System.Exception)

CommandQueueHandleDefaultRes<System.Int32>#0: 2
	CommandQueueHostQuickFunc<System.Int32>#1: Int32 <>lambda*()
	Boolean <>lambda*(System.Exception)

CommandQueueHandleReplaceRes<System.Int32>#0
	CommandQueueHostQuickFunc<System.Int32>#1: Int32 <>lambda*()
	Int32 <>lambda*(System.Collections.Generic.List`1[System.Exception])

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 


