


#DelegateCount
3

#ExpOtp
CastQueue<integer,Object>#0
	CommandQueueHostBackgoundFunc<integer>#1: function lambda: integer

CommandQueueHostBackgoundFunc<integer>#0: function lambda: integer

CastQueue<integer,Nullable<integer>>#0
	CommandQueueHostBackgoundFunc<integer>#1: function lambda: integer

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


