


#DelegateCount
3

#ExpExecOtp
CastQueue<integer,Object>#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer

CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#0: function lambda: integer

CastQueue<integer,Nullable<integer>>#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer

#ReqModules
OpenCLABC


