


#ReqModules
OpenCLABC

#ExpOtp
CastQueue<System.Int32, System.Object>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()

CommandQueueHostBackgoundFunc<System.Int32>#0: Int32 <>lambda*()

CastQueue<System.Int32, System.Nullable`1[System.Int32]>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 


