


#ReqModules
OpenCLABC

#ExpOtp
raise2
System.Exception: TestOK
   at Spec3.<>local_variables_class_1.<>lambda3()
   at OpenCLABC_implementation______.CommandQueueHostProc.ExecFunc(Object o, Context c)
   at OpenCLABC_implementation______.<>local_variables_class_13`2.<>lambda22()
   at OpenCLABC_implementation______.<>local_variables_class_5.<>lambda14()
raise1
========================================
raise1
System.Exception: TestOK
   at Spec3.<>local_variables_class_1.<>lambda2()
   at OpenCLABC_implementation______.CommandQueueHostProc.ExecFunc(Object o, Context c)
   at OpenCLABC_implementation______.<>local_variables_class_13`2.<>lambda22()
   at OpenCLABC_implementation______.<>local_variables_class_5.<>lambda14()
raise2


