


#DelegateCount
5

#ExpExecOtp
1 2 3 4 5 6 7 8 9 10
[EventDebug]: 3 event's created 
[QueueDebug]: 2 queue's created 
[ExecDebug]: 1 cache entries created 
[QueueResNil]: 2 
[QueueRes<T>]: 5 
	QueueResValDirect<array of integer>: 1 
	QueueResValDirect<CLArray<integer>>: 2 
	QueueResValDirect<CLKernel>: 1 
	QueueResValDirect<integer>: 1 

#ReqModules
OpenCLABC

#TestMode
Comp+Exec


