


#ReqModules
OpenCLABC

#ExpOtp
CommandQueueHostBackgoundFunc<integer>#0: function lambda: integer

CommandQueueHostBackgoundProc#0: procedure lambda

CommandQueueHostBackgoundFuncC<integer>#0: function lambda(с: Context): integer

CommandQueueHostBackgoundProcC#0: procedure lambda(с: Context)

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#DelegateCount
3


