


#DelegateCount
3

#ExpExecOtp
CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#0: function lambda: integer

CommandQueueHostQuickProc<SimpleProc0Container>#0: procedure lambda

CommandQueueHostQuickFunc<integer,SimpleFunc0ContainerC<integer>>#0: function lambda(с: CLContext): integer

CommandQueueHostQuickProc<SimpleProc0ContainerC>#0: procedure lambda(с: CLContext)

CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#0: function lambda: integer

CommandQueueHostThreadedProc<SimpleProc0Container>#0: procedure lambda

CommandQueueHostThreadedFunc<integer,SimpleFunc0ContainerC<integer>>#0: function lambda(с: CLContext): integer

CommandQueueHostThreadedProc<SimpleProc0ContainerC>#0: procedure lambda(с: CLContext)

#ReqModules
OpenCLABC


