


#DelegateCount
3

#ExpOtp
System.Exception: TestOK
   at BranchCancel.Program.<>lambda*() in *\POCGL\Tests\Exec\CLABC\02#Выполнение очередей\11#Finally+Handle\BranchCancel.pas:line *
   at OpenCLABC_implementation______.CommandQueueHostBackgoundProc.ExecProc(Context c) in *\POCGL\Tests\LibSource\OpenCLABC.pas:line *
   at OpenCLABC_implementation______.<>local_variables_class_*`1.<>lambda*() in *\POCGL\Tests\LibSource\OpenCLABC.pas:line *
[EventDebug]: 3 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


