


#ReqModules
OpenCLABC

#ExpOtp
ConvSyncQueueArray<System.Object, System.String>#0
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#1 { nil }
	OpenCLABC_implementation______.<>local_variables_class_*`2[System.Object,System.String] => System.String <>lambda*(System.Object[], OpenCLABC.Context)

ConvAsyncQueueArray<System.Object, System.String>#0
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#1 { nil }
	OpenCLABC_implementation______.<>local_variables_class_*`2[System.Object,System.String] => System.String <>lambda*(System.Object[], OpenCLABC.Context)


