


#ReqModules
OpenCLABC

#ExpOtp
ConvSyncQueueArray<System.Object, System.String>#0 => System.Func`3[System.Object[],OpenCLABC.Context,System.String]
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#2 { nil }

ConvAsyncQueueArray<System.Object, System.String>#0 => System.Func`3[System.Object[],OpenCLABC.Context,System.String]
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#2 { nil }


