


#ReqModules
OpenCLABC

#ExpOtp
ConvSyncQueueArray<System.Object, System.Object>#0
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#1 { nil }
	OpenCLABC_implementation______.<>local_variables_class_*`1[System.Object] => System.Object <>lambda*(System.Object[], OpenCLABC.Context)

ConvAsyncQueueArray<System.Object, System.Object>#0
	ConstQueue<System.Object>#1 { nil }
	ConstQueue<System.Object>#1 { nil }
	OpenCLABC_implementation______.<>local_variables_class_*`1[System.Object] => System.Object <>lambda*(System.Object[], OpenCLABC.Context)


