


#ReqModules
OpenCLABC

#ExpOtp
SimpleSyncQueueArray<System.Int32>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()

SimpleAsyncQueueArray<System.Int32>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()

SimpleAsyncQueueArray<System.Int32>#0
	SimpleSyncQueueArray<System.Int32>#1
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
	SimpleSyncQueueArray<System.Int32>#3
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()

SimpleSyncQueueArray<System.Int32>#0
	SimpleAsyncQueueArray<System.Int32>#1
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
	SimpleAsyncQueueArray<System.Int32>#3
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()


