


#ReqModules
OpenCLABC

#ExpOtp
SimpleSyncQueueArray<System.Int32>#0
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()

SimpleAsyncQueueArray<System.Int32>#0
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostFunc<System.Int32>#1: Int32 <>lambda*()

SimpleAsyncQueueArray<System.Int32>#0
	SimpleSyncQueueArray<System.Int32>#1
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
	SimpleSyncQueueArray<System.Int32>#3
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()

SimpleSyncQueueArray<System.Int32>#0
	SimpleAsyncQueueArray<System.Int32>#1
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
	SimpleAsyncQueueArray<System.Int32>#3
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()
		CommandQueueHostFunc<System.Int32>#2: Int32 <>lambda*()


