


#ReqModules
OpenCLABC

#ExpOtp
ConstQueue<System.Object>#0 System.Byte{ 5 }

SimpleAsyncQueueArray<System.Object>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CastQueue<System.Int32, System.Object>#2
		CommandQueueHostBackgoundFunc<System.Int32>#3: Int32 <>lambda*()

MemorySegmentCCQ#0
	CCCObj => MemorySegment[*] of size 1
	QueueCommand
		CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()


