


#ReqModules
OpenCLABC

#ExpOtp
SimpleAsyncQueueArray<System.Object>#0
	ConstQueue<System.Object>#1 System.Byte{ 5 }

SimpleAsyncQueueArray<System.Object>#0
	CommandQueueHostFunc<System.Int32>#1: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)
	CastQueue<System.Object>#2
		CommandQueueHostFunc<System.Int32>#3: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)

MemorySegmentCCQ#0
	CCCObj => MemorySegment[*] of size 1
	QueueCommand
		CommandQueueHostFunc<System.Int32>#1: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)


