


#DelegateCount
3

#ExpOtp
SimpleSyncQueueArray<integer>#0
	CommandQueueHostBackgoundFunc<integer>#1: function lambda: integer
	CommandQueueHostBackgoundFunc<integer>#2: function lambda: integer

SimpleAsyncQueueArray<integer>#0
	CommandQueueHostBackgoundFunc<integer>#1: function lambda: integer
	CommandQueueHostBackgoundFunc<integer>#2: function lambda: integer

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


