


#ReqModules
OpenCLABC

#ExpOtp
SimpleSyncQueueArray<System.Int32>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()

SimpleAsyncQueueArray<System.Int32>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CommandQueueHostBackgoundFunc<System.Int32>#2: Int32 <>lambda*()

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 


