


#DelegateCount
3

#ExpOtp
CommandQueueQuickArray<Object,array of Object,QueueArraySyncInvoker,SimpleFuncContainer<array of Object,array of Object>,QueueArrayWorkConvert<Object,array of Object,SimpleFuncContainer<array of Object,array of Object>>,TBooleanFalseFlag>#0
	ConstQueue<Object>#1: { nil }
	ConstQueue<Object>#1: { nil }
	function lambda(a: array of Object): array of Object

CommandQueueQuickArray<Object,array of Object,QueueArrayAsyncInvoker,SimpleFuncContainer<array of Object,array of Object>,QueueArrayWorkConvert<Object,array of Object,SimpleFuncContainer<array of Object,array of Object>>,TBooleanFalseFlag>#0
	ConstQueue<Object>#1: { nil }
	ConstQueue<Object>#1: { nil }
	function lambda(a: array of Object): array of Object

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


