


#ReqModules
OpenCLABC

#ExpOtp
CastQueue<System.Byte, System.Object>#0
	ConstQueue<System.Byte>#1: 5

SimpleAsyncQueueArray<System.Object>#0
	CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()
	CastQueue<System.Int32, System.Object>#2
		CommandQueueHostBackgoundFunc<System.Int32>#3: Int32 <>lambda*()

MemorySegmentCCQ#0
	CCCObj: MemorySegment[*] of size 1
	QueueCommand
		CommandQueueHostBackgoundFunc<System.Int32>#1: Int32 <>lambda*()

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 


