


#DelegateCount
3

#ExpExecOtp
CommandQueueHostThreadedProc<SimpleProc0Container>#0: procedure lambda

SimpleSyncQueueArrayNil#0
	CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	ConstQueueNil#2

SimpleSyncQueueArrayNil#0
	CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	CommandQueueHostThreadedProc<SimpleProc0Container>#2: procedure lambda
 

#ReqModules
OpenCLABC


