


#DelegateCount
3

#ExpOtp
CommandQueueHostThreadedProc<SimpleProc0Container>#0: procedure lambda

SimpleSyncQueueArrayNil#0
	CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	ConstQueueNil#2

SimpleSyncQueueArrayNil#0
	CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	CommandQueueHostThreadedProc<SimpleProc0Container>#2: procedure lambda
 
[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


