


#ReqModules
OpenCLABC

#ExpOtp
>>> Const

Buffer:
OpenCLABCBase_implementation______.KernelArgBuffer
Record:
OpenCLABCBase_implementation______.KernelArgRecord`1[System.Int32]
Ptr:
OpenCLABCBase_implementation______.KernelArgPtr

>>> Invokable

Buffer:
OpenCLABCBase_implementation______.KernelArgBufferCQ
Record:
OpenCLABCBase_implementation______.KernelArgRecord`1[System.Int32]
Ptr:
OpenCLABCBase_implementation______.KernelArgPtrCQ

#ExpErr
Compile errors:
[22,3] KernelArg1.pas: 'CommandQueue<integer>' must be value type


