


#ReqModules
OpenCLABC

#ExpOtp
>>> Const

Buffer:
OpenCLABCBase_implementation______.KernelArgBuffer
Record:
OpenCLABCBase_implementation______.KernelArgRecord`1[System.Int32]
Ptr:
OpenCLABCBase_implementation______.KernelArgPtr

>>> Invokable

Buffer:
OpenCLABCBase_implementation______.KernelArgBufferCQ
Record:
OpenCLABCBase_implementation______.KernelArgRecord`1[System.Int32]
Ptr:
OpenCLABCBase_implementation______.KernelArgPtrCQ


