


#ReqModules
OpenCLABC

#ExpOtp
Logging uses of cl_command_queue[*] 
OpenCLABC_implementation______.MemorySegmentCommandWriteValue`1[System.Byte]
OpenCLABC_implementation______.MemorySegmentCommandWriteValue`1[System.Double]
----- last q -----
============================== 
Logging uses of cl_command_queue[*] 
OpenCLABC_implementation______.MemorySegmentCommandWriteValue`1[System.UInt16]
----- return -----
============================== 


