


#DelegateCount
4

#ExpOtp
Global 
|	Managed 
|	|	Array 
|	|	|	KernelArgGlobalArray<byte>: cl_mem[*] 
|	|	Array2 
|	|	|	KernelArgGlobalArray2<byte>: cl_mem[*] 
|	|	Array3 
|	|	|	KernelArgGlobalArray3<byte>: cl_mem[*] 
|	|	ArraySegment 
|	|	|	KernelArgGlobalArraySegment<byte>: cl_mem[*] 
|	NativeArea 
|	|	NativeMemoryArea 
|	|	|	KernelArgGlobalNativeMemoryArea: cl_mem[*] 
|	|	NativeValueArea 
|	|	|	KernelArgGlobalNativeValueArea<byte>: cl_mem[*] 
|	|	NativeArrayArea 
|	|	|	KernelArgGlobalNativeArrayArea<byte>: cl_mem[*] 
|	Native 
|	|	NativeMemory 
|	|	|	KernelArgGlobalNativeMemory: cl_mem[*] 
|	|	NativeValue 
|	|	|	KernelArgGlobalNativeValue<byte>: cl_mem[*] 
|	|	NativeArray 
|	|	|	KernelArgGlobalNativeArray<byte>: cl_mem[*] 
|	CL 
|	|	CLMemory 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ParameterQueue<CLMemory>#0["cl_mem"]: Default=CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		CLMemoryCCQ#0 
|	|	|			CCCObj<CLMemory>: CLMemory[*] of size 1 
|	|	CLValue 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ParameterQueue<CLValue<byte>>#0["cl_val"]: Default=CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		CLValueCCQ<byte>#0 
|	|	|			CCCObj<CLValue<byte>>: CLValue<byte>[*] 
|	|	CLArray 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ParameterQueue<CLArray<byte>>#0["cl_arr"]: Default=CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		CLArrayCCQ<byte>#0 
|	|	|			CCCObj<CLArray<byte>>: CLArray<byte>[*] of length 4 
Constant 
|	Managed 
|	|	Array 
|	|	|	KernelArgConstantArray<byte>: cl_mem[*] 
|	|	Array2 
|	|	|	KernelArgConstantArray2<byte>: cl_mem[*] 
|	|	Array3 
|	|	|	KernelArgConstantArray3<byte>: cl_mem[*] 
|	|	ArraySegment 
|	|	|	KernelArgConstantArraySegment<byte>: cl_mem[*] 
|	NativeArea 
|	|	NativeMemoryArea 
|	|	|	KernelArgConstantNativeMemoryArea: cl_mem[*] 
|	|	NativeValueArea 
|	|	|	KernelArgConstantNativeValueArea<byte>: cl_mem[*] 
|	|	NativeArrayArea 
|	|	|	KernelArgConstantNativeArrayArea<byte>: cl_mem[*] 
|	Native 
|	|	NativeMemory 
|	|	|	KernelArgConstantNativeMemory: cl_mem[*] 
|	|	NativeValue 
|	|	|	KernelArgConstantNativeValue<byte>: cl_mem[*] 
|	|	NativeArray 
|	|	|	KernelArgConstantNativeArray<byte>: cl_mem[*] 
|	CL 
|	|	CLMemory 
|	|	|	KernelArgConstantCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgConstantCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgConstantCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgConstantCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgConstantCLMemory 
|	|	|		ParameterQueue<CLMemory>#0["cl_mem"]: Default=CLMemory[*] of size 1 
|	|	|	KernelArgConstantCLMemory 
|	|	|		CLMemoryCCQ#0 
|	|	|			CCCObj<CLMemory>: CLMemory[*] of size 1 
|	|	CLValue 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		ParameterQueue<CLValue<byte>>#0["cl_val"]: Default=CLValue<byte>[*] 
|	|	|	KernelArgConstantCLValue<byte> 
|	|	|		CLValueCCQ<byte>#0 
|	|	|			CCCObj<CLValue<byte>>: CLValue<byte>[*] 
|	|	CLArray 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		ParameterQueue<CLArray<byte>>#0["cl_arr"]: Default=CLArray<byte>[*] of length 4 
|	|	|	KernelArgConstantCLArray<byte> 
|	|	|		CLArrayCCQ<byte>#0 
|	|	|			CCCObj<CLArray<byte>>: CLArray<byte>[*] of length 4 
Local 
|	FromBytes 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 123 
|	|	KernelArgLocalBytes 
|	|		CommandQueueHostQuickFunc<System.UIntPtr,SimpleFunc0Container<System.UIntPtr>>#0: function lambda: System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 123 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<longword,System.UIntPtr,SimpleFuncContainer<longword,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<longword,SimpleFunc0Container<longword>>#1: function lambda: longword 
|	|			function lambda(bytes: longword): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 123 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer 
|	|			function lambda(bytes: integer): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 123 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<uint64,System.UIntPtr,SimpleFuncContainer<uint64,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<uint64,SimpleFunc0Container<uint64>>#1: function lambda: uint64 
|	|			function lambda(bytes: uint64): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 123 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<int64,System.UIntPtr,SimpleFuncContainer<int64,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<int64,SimpleFunc0Container<int64>>#1: function lambda: int64 
|	|			function lambda(bytes: int64): System.UIntPtr 
|	FromItemCount 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 256 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<longword,System.UIntPtr,SimpleFuncContainer<longword,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<longword,SimpleFunc0Container<longword>>#1: function lambda: longword 
|	|			function lambda(item_count: longword): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 256 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer 
|	|			function lambda(item_count: integer): System.UIntPtr 
|	LikeArray 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 4 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<array of byte,integer,SimpleFuncContainer<array of byte,integer>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<array of byte,SimpleFunc0Container<array of byte>>#2: function lambda: array of byte 
|	|				function lambda(a: array of byte): integer 
|	|			function lambda(item_count: integer): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 6 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<array [,] of byte,integer,SimpleFuncContainer<array [,] of byte,integer>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<array [,] of byte,SimpleFunc0Container<array [,] of byte>>#2: function lambda: array [,] of byte 
|	|				function lambda(a: array [,] of byte): integer 
|	|			function lambda(item_count: integer): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 24 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<array [,,] of byte,integer,SimpleFuncContainer<array [,,] of byte,integer>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<array [,,] of byte,SimpleFunc0Container<array [,,] of byte>>#2: function lambda: array [,,] of byte 
|	|				function lambda(a: array [,,] of byte): integer 
|	|			function lambda(item_count: integer): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 5 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<longword,System.UIntPtr,SimpleFuncContainer<longword,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<NativeArrayArea<byte>,longword,SimpleFuncContainer<NativeArrayArea<byte>,longword>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<NativeArrayArea<byte>,SimpleFunc0Container<NativeArrayArea<byte>>>#2: function lambda: NativeArrayArea<byte> 
|	|				function lambda(a: NativeArrayArea<byte>): longword 
|	|			function lambda(item_count: longword): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 4 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<longword,System.UIntPtr,SimpleFuncContainer<longword,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<NativeArray<byte>,longword,SimpleFuncContainer<NativeArray<byte>,longword>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<NativeArray<byte>,SimpleFunc0Container<NativeArray<byte>>>#2: function lambda: NativeArray<byte> 
|	|				function lambda(a: NativeArray<byte>): longword 
|	|			function lambda(item_count: longword): System.UIntPtr 
|	|	KernelArgLocalBytes 
|	|		ConstQueue<System.UIntPtr>#0: 4 
|	|	KernelArgLocalBytes 
|	|		CommandQueueThenQuickConvert<integer,System.UIntPtr,SimpleFuncContainer<integer,System.UIntPtr>,TBooleanTrueFlag>#0 
|	|			CommandQueueThenQuickConvert<CLArray<byte>,integer,SimpleFuncContainer<CLArray<byte>,integer>,TBooleanTrueFlag>#1 
|	|				CommandQueueHostQuickFunc<CLArray<byte>,SimpleFunc0Container<CLArray<byte>>>#2: function lambda: CLArray<byte> 
|	|				function lambda(a: CLArray<byte>): integer 
|	|			function lambda(item_count: integer): System.UIntPtr 
Private 
|	Managed 
|	|	Array 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ParameterQueue<array of byte>#0["a"]: Default=[1,2,3,4] 
|	|	Array2 
|	|	|	KernelArgPrivateArray2<byte> 
|	|	|		ConstQueue<array [,] of byte>#0: [[1,2,3],[4,5,6]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: array [,] of byte{ [[1,2,3],[4,5,6]] } 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array [,] of byte>#0: [[1,2,3],[4,5,6]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array [,] of byte>#0: [[1,2,3],[4,5,6]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ParameterQueue<array [,] of byte>#0["a2"]: Default=[[1,2,3],[4,5,6]] 
|	|	Array3 
|	|	|	KernelArgPrivateArray3<byte> 
|	|	|		ConstQueue<array [,,] of byte>#0: [[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0],[1,2,3,4]]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array of byte>#0: array [,,] of byte{ [[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0],[1,2,3,4]]] } 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array [,,] of byte>#0: [[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0],[1,2,3,4]]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ConstQueue<array [,,] of byte>#0: [[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0],[1,2,3,4]]] 
|	|	|	KernelArgPrivateArray<byte> 
|	|	|		ParameterQueue<array [,,] of byte>#0["a3"]: Default=[[[1,2,3,4],[5,6,7,8],[9,0,1,2]],[[3,4,5,6],[7,8,9,0],[1,2,3,4]]] 
|	|	ArraySegment 
|	|	|	KernelArgPrivateArraySegment<byte> 
|	|	|		ConstQueue<ArraySegment<byte>>#0: [2,3] 
|	|	|	KernelArgPrivateArraySegment<byte> 
|	|	|		ConstQueue<ArraySegment<byte>>#0: [2,3] 
|	|	|	KernelArgPrivateArraySegment<byte> 
|	|	|		ConstQueue<ArraySegment<byte>>#0: [2,3] 
|	|	|	KernelArgPrivateArraySegment<byte> 
|	|	|		ConstQueue<ArraySegment<byte>>#0: [2,3] 
|	|	|	KernelArgPrivateArraySegment<byte> 
|	|	|		ParameterQueue<ArraySegment<byte>>#0["seg"]: Default=[2,3] 
|	NativeArea 
|	|	NativeMemoryArea 
|	|	|	KernelArgPrivateNativeMemoryArea 
|	|	|		ConstQueue<NativeMemoryArea>#0: NativeMemoryArea:$1[2] 
|	|	|	KernelArgPrivateNativeMemoryArea 
|	|	|		ConstQueue<NativeMemoryArea>#0: NativeMemoryArea:$1[2] 
|	|	|	KernelArgPrivateNativeMemoryArea 
|	|	|		ConstQueue<NativeMemoryArea>#0: NativeMemoryArea:$1[2] 
|	|	|	KernelArgPrivateNativeMemoryArea 
|	|	|		ConstQueue<NativeMemoryArea>#0: NativeMemoryArea:$1[2] 
|	|	|	KernelArgPrivateNativeMemoryArea 
|	|	|		ParameterQueue<NativeMemoryArea>#0["ntv_mem_area"]: Default=NativeMemoryArea:$1[2] 
|	|	NativeValueArea 
|	|	|	KernelArgPrivateNativeValueArea<byte> 
|	|	|		ConstQueue<NativeValueArea<byte>>#0: NativeValueArea<byte>:$3 
|	|	|	KernelArgPrivateNativeValueArea<byte> 
|	|	|		ConstQueue<NativeValueArea<byte>>#0: NativeValueArea<byte>:$3 
|	|	|	KernelArgPrivateNativeValueArea<byte> 
|	|	|		ConstQueue<NativeValueArea<byte>>#0: NativeValueArea<byte>:$3 
|	|	|	KernelArgPrivateNativeValueArea<byte> 
|	|	|		ConstQueue<NativeValueArea<byte>>#0: NativeValueArea<byte>:$3 
|	|	|	KernelArgPrivateNativeValueArea<byte> 
|	|	|		ParameterQueue<NativeValueArea<byte>>#0["ntv_val_area"]: Default=NativeValueArea<byte>:$3 
|	|	NativeArrayArea 
|	|	|	KernelArgPrivateNativeArrayArea<byte> 
|	|	|		ConstQueue<NativeArrayArea<byte>>#0: NativeArrayArea<byte>:$4[5] 
|	|	|	KernelArgPrivateNativeArrayArea<byte> 
|	|	|		ConstQueue<NativeArrayArea<byte>>#0: NativeArrayArea<byte>:$4[5] 
|	|	|	KernelArgPrivateNativeArrayArea<byte> 
|	|	|		ConstQueue<NativeArrayArea<byte>>#0: NativeArrayArea<byte>:$4[5] 
|	|	|	KernelArgPrivateNativeArrayArea<byte> 
|	|	|		ConstQueue<NativeArrayArea<byte>>#0: NativeArrayArea<byte>:$4[5] 
|	|	|	KernelArgPrivateNativeArrayArea<byte> 
|	|	|		ParameterQueue<NativeArrayArea<byte>>#0["ntv_arr_area"]: Default=NativeArrayArea<byte>:$4[5] 
|	Native 
|	|	NativeMemory 
|	|	|	KernelArgPrivateNativeMemory 
|	|	|		ConstQueue<NativeMemory>#0: NativeMemory:$*[2] 
|	|	|	KernelArgPrivateNativeMemory 
|	|	|		ConstQueue<NativeMemory>#0: NativeMemory:$*[2] 
|	|	|	KernelArgPrivateNativeMemory 
|	|	|		ConstQueue<NativeMemory>#0: NativeMemory:$*[2] 
|	|	|	KernelArgPrivateNativeMemory 
|	|	|		ConstQueue<NativeMemory>#0: NativeMemory:$*[2] 
|	|	|	KernelArgPrivateNativeMemory 
|	|	|		ParameterQueue<NativeMemory>#0["ntv_mem"]: Default=NativeMemory:$*[2] 
|	|	NativeValue 
|	|	|	KernelArgPrivateNativeValue<byte> 
|	|	|		ConstQueue<NativeValue<byte>>#0: NativeValue<byte>{ 123 } 
|	|	|	KernelArgPrivateNativeValue<byte> 
|	|	|		ConstQueue<NativeValue<byte>>#0: NativeValue<byte>{ 123 } 
|	|	|	KernelArgPrivateNativeValue<byte> 
|	|	|		ConstQueue<NativeValue<byte>>#0: NativeValue<byte>{ 123 } 
|	|	|	KernelArgPrivateNativeValue<byte> 
|	|	|		ConstQueue<NativeValue<byte>>#0: NativeValue<byte>{ 123 } 
|	|	|	KernelArgPrivateNativeValue<byte> 
|	|	|		ParameterQueue<NativeValue<byte>>#0["ntv_val"]: Default=NativeValue<byte>{ 123 } 
|	|	NativeArray 
|	|	|	KernelArgPrivateNativeArray<byte> 
|	|	|		ConstQueue<NativeArray<byte>>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateNativeArray<byte> 
|	|	|		ConstQueue<NativeArray<byte>>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateNativeArray<byte> 
|	|	|		ConstQueue<NativeArray<byte>>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateNativeArray<byte> 
|	|	|		ConstQueue<NativeArray<byte>>#0: [1,2,3,4] 
|	|	|	KernelArgPrivateNativeArray<byte> 
|	|	|		ParameterQueue<NativeArray<byte>>#0["ntv_arr"]: Default=[1,2,3,4] 
|	Value 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<byte> 
|	|		ConstQueue<byte>#0: 1 
|	|	KernelArgPrivateValue<byte> 
|	|		ParameterQueue<byte>#0["val"]: Default=1 
Generic 
|	Managed 
|	|	Array 
|	|	|	KernelArgGlobalArray<byte>: cl_mem[*] 
|	|	Array2 
|	|	|	KernelArgGlobalArray2<byte>: cl_mem[*] 
|	|	Array3 
|	|	|	KernelArgGlobalArray3<byte>: cl_mem[*] 
|	|	ArraySegment 
|	|	|	KernelArgGlobalArraySegment<byte>: cl_mem[*] 
|	NativeArea 
|	|	NativeMemoryArea 
|	|	|	KernelArgGlobalNativeMemoryArea: cl_mem[*] 
|	|	NativeValueArea 
|	|	|	KernelArgGlobalNativeValueArea<byte>: cl_mem[*] 
|	|	NativeArrayArea 
|	|	|	KernelArgGlobalNativeArrayArea<byte>: cl_mem[*] 
|	Native 
|	|	NativeMemory 
|	|	|	KernelArgGlobalNativeMemory: cl_mem[*] 
|	|	NativeValue 
|	|	|	KernelArgGlobalNativeValue<byte>: cl_mem[*] 
|	|	NativeArray 
|	|	|	KernelArgGlobalNativeArray<byte>: cl_mem[*] 
|	CL 
|	|	CLMemory 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ConstQueue<CLMemory>#0: CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		ParameterQueue<CLMemory>#0["cl_mem"]: Default=CLMemory[*] of size 1 
|	|	|	KernelArgGlobalCLMemory 
|	|	|		CLMemoryCCQ#0 
|	|	|			CCCObj<CLMemory>: CLMemory[*] of size 1 
|	|	CLValue 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ConstQueue<CLValue<byte>>#0: CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		ParameterQueue<CLValue<byte>>#0["cl_val"]: Default=CLValue<byte>[*] 
|	|	|	KernelArgGlobalCLValue<byte> 
|	|	|		CLValueCCQ<byte>#0 
|	|	|			CCCObj<CLValue<byte>>: CLValue<byte>[*] 
|	|	CLArray 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ConstQueue<CLArray<byte>>#0: CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		ParameterQueue<CLArray<byte>>#0["cl_arr"]: Default=CLArray<byte>[*] of length 4 
|	|	|	KernelArgGlobalCLArray<byte> 
|	|	|		CLArrayCCQ<byte>#0 
|	|	|			CCCObj<CLArray<byte>>: CLArray<byte>[*] of length 4 
|	Value 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<integer> 
|	|		ConstQueue<integer>#0: 1 
|	|	KernelArgPrivateValue<byte> 
|	|		ConstQueue<byte>#0: 1 
|	|	KernelArgPrivateValue<byte> 
|	|		ParameterQueue<byte>#0["val"]: Default=1 
[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


