


#DelegateCount
5

#ExpExecOtp
OpenCLABC.CLProgramCode 
OpenCLABC.CLCodeProperties 
CLKernel[k] from CLProgramCode[*]
============================== 
kernel void k(int x) {} 
============================== 
True 
True 
OpenCLABC.CLProgramCode 
OpenCLABC.CLCodeProperties 
CLKernel[k] from CLProgramCode[*]
============================== 
kernel void k(int x) {} 
============================== 

#ReqModules
OpenCLABC


