


#ReqModules
OpenCLABC

#ExpOtp
CastQueue<System.Object>#0
	CommandQueueHostFunc<System.Int32>#1: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)

CastQueue<System.Int32>#0
	CastQueue<System.Object>#1
		CommandQueueHostFunc<System.Int32>#2: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)

CastQueue<System.Nullable`1[System.Int32]>#0
	CastQueue<System.Object>#1
		CommandQueueHostFunc<System.Int32>#2: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)


