


#ReqModules
OpenCLABC

#ExpOtp
CastQueue<System.Int32, System.Object>#0
	CommandQueueHostFunc<System.Int32>#1: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)

CommandQueueHostFunc<System.Int32>#0: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)

CastQueue<System.Int32, System.Nullable`1[System.Int32]>#0
	CommandQueueHostFunc<System.Int32>#1: OpenCLABC_implementation______.<>local_variables_class_*`1[System.Int32] => Int32 <>lambda*(OpenCLABC.Context)


