


#DelegateCount
5

#ExpExecOtp
[EventDebug]: 10 event's created 
[QueueDebug]: 2 queue's created 
[QueueResNil]: 15 
[QueueRes<T>]: 23 
	QueueResValDirect<array of integer>: 4 
	QueueResValDirect<boolean>: 1 
	QueueResValDirect<CLArray<integer>>: 4 
	QueueResValDirect<CLKernel>: 2 
	QueueResValDirect<CLProgramCode>: 2 
	QueueResValDirect<integer>: 2 
	QueueResValWrap<CLArray<integer>>: 6 
	QueueResValWrap<CLKernel>: 2 

#ReqModules
OpenCLABC


