


void glVertex2s(glshort v1, glshort v2);
void glVertex2sv(glshort * v);
void glVertex2i(glint v1, glint v2);
void glVertex2iv(glint * v);
void glVertex2f(glfloat v1, glfloat v2);
void glVertex2fv(glfloat * v);
void glVertex2d(gldouble v1, gldouble v2);
void glVertex2dv(gldouble * v);
void glVertex3s(glshort v1, glshort v2, glshort v3);
void glVertex3sv(glshort * v);
void glVertex3i(glint v1, glint v2, glint v3);
void glVertex3iv(glint * v);
void glVertex3f(glfloat v1, glfloat v2, glfloat v3);
void glVertex3fv(glfloat * v);
void glVertex3d(gldouble v1, gldouble v2, gldouble v3);
void glVertex3dv(gldouble * v);
void glVertex4s(glshort v1, glshort v2, glshort v3, glshort v4);
void glVertex4sv(glshort * v);
void glVertex4i(glint v1, glint v2, glint v3, glint v4);
void glVertex4iv(glint * v);
void glVertex4f(glfloat v1, glfloat v2, glfloat v3, glfloat v4);
void glVertex4fv(glfloat * v);
void glVertex4d(gldouble v1, gldouble v2, gldouble v3, gldouble v4);
void glVertex4dv(gldouble * v);

void glTexCoord1s(glshort v1);
void glTexCoord1sv(glshort * v);
void glTexCoord1i(glint v1);
void glTexCoord1iv(glint * v);
void glTexCoord1f(glfloat v1);
void glTexCoord1fv(glfloat * v);
void glTexCoord1d(gldouble v1);
void glTexCoord1dv(gldouble * v);
void glTexCoord2s(glshort v1, glshort v2);
void glTexCoord2sv(glshort * v);
void glTexCoord2i(glint v1, glint v2);
void glTexCoord2iv(glint * v);
void glTexCoord2f(glfloat v1, glfloat v2);
void glTexCoord2fv(glfloat * v);
void glTexCoord2d(gldouble v1, gldouble v2);
void glTexCoord2dv(gldouble * v);
void glTexCoord3s(glshort v1, glshort v2, glshort v3);
void glTexCoord3sv(glshort * v);
void glTexCoord3i(glint v1, glint v2, glint v3);
void glTexCoord3iv(glint * v);
void glTexCoord3f(glfloat v1, glfloat v2, glfloat v3);
void glTexCoord3fv(glfloat * v);
void glTexCoord3d(gldouble v1, gldouble v2, gldouble v3);
void glTexCoord3dv(gldouble * v);
void glTexCoord4s(glshort v1, glshort v2, glshort v3, glshort v4);
void glTexCoord4sv(glshort * v);
void glTexCoord4i(glint v1, glint v2, glint v3, glint v4);
void glTexCoord4iv(glint * v);
void glTexCoord4f(glfloat v1, glfloat v2, glfloat v3, glfloat v4);
void glTexCoord4fv(glfloat * v);
void glTexCoord4d(gldouble v1, gldouble v2, gldouble v3, gldouble v4);
void glTexCoord4dv(gldouble * v);

void glNormal3b(glbyte v1, glbyte v2, glbyte v3);
void glNormal3bv(glbyte * v);
void glNormal3s(glshort v1, glshort v2, glshort v3);
void glNormal3sv(glshort * v);
void glNormal3i(glint v1, glint v2, glint v3);
void glNormal3iv(glint * v);
void glNormal3f(glfloat v1, glfloat v2, glfloat v3);
void glNormal3fv(glfloat * v);
void glNormal3d(gldouble v1, gldouble v2, gldouble v3);
void glNormal3dv(gldouble * v);

void glColor3b(glbyte v1, glbyte v2, glbyte v3);
void glColor3bv(glbyte * v);
void glColor3s(glshort v1, glshort v2, glshort v3);
void glColor3sv(glshort * v);
void glColor3i(glint v1, glint v2, glint v3);
void glColor3iv(glint * v);
void glColor3ub(glubyte v1, glubyte v2, glubyte v3);
void glColor3ubv(glubyte * v);
void glColor3us(glushort v1, glushort v2, glushort v3);
void glColor3usv(glushort * v);
void glColor3ui(gluint v1, gluint v2, gluint v3);
void glColor3uiv(gluint * v);
void glColor3f(glfloat v1, glfloat v2, glfloat v3);
void glColor3fv(glfloat * v);
void glColor3d(gldouble v1, gldouble v2, gldouble v3);
void glColor3dv(gldouble * v);
void glColor4b(glbyte v1, glbyte v2, glbyte v3, glbyte v4);
void glColor4bv(glbyte * v);
void glColor4s(glshort v1, glshort v2, glshort v3, glshort v4);
void glColor4sv(glshort * v);
void glColor4i(glint v1, glint v2, glint v3, glint v4);
void glColor4iv(glint * v);
void glColor4ub(glubyte v1, glubyte v2, glubyte v3, glubyte v4);
void glColor4ubv(glubyte * v);
void glColor4us(glushort v1, glushort v2, glushort v3, glushort v4);
void glColor4usv(glushort * v);
void glColor4ui(gluint v1, gluint v2, gluint v3, gluint v4);
void glColor4uiv(gluint * v);
void glColor4f(glfloat v1, glfloat v2, glfloat v3, glfloat v4);
void glColor4fv(glfloat * v);
void glColor4d(gldouble v1, gldouble v2, gldouble v3, gldouble v4);
void glColor4dv(gldouble * v);

void glRasterPos2s(glshort v1, glshort v2);
void glRasterPos2sv(glshort * v);
void glRasterPos2i(glint v1, glint v2);
void glRasterPos2iv(glint * v);
void glRasterPos2f(glfloat v1, glfloat v2);
void glRasterPos2fv(glfloat * v);
void glRasterPos2d(gldouble v1, gldouble v2);
void glRasterPos2dv(gldouble * v);
void glRasterPos3s(glshort v1, glshort v2, glshort v3);
void glRasterPos3sv(glshort * v);
void glRasterPos3i(glint v1, glint v2, glint v3);
void glRasterPos3iv(glint * v);
void glRasterPos3f(glfloat v1, glfloat v2, glfloat v3);
void glRasterPos3fv(glfloat * v);
void glRasterPos3d(gldouble v1, gldouble v2, gldouble v3);
void glRasterPos3dv(gldouble * v);
void glRasterPos4s(glshort v1, glshort v2, glshort v3, glshort v4);
void glRasterPos4sv(glshort * v);
void glRasterPos4i(glint v1, glint v2, glint v3, glint v4);
void glRasterPos4iv(glint * v);
void glRasterPos4f(glfloat v1, glfloat v2, glfloat v3, glfloat v4);
void glRasterPos4fv(glfloat * v);
void glRasterPos4d(gldouble v1, gldouble v2, gldouble v3, gldouble v4);
void glRasterPos4dv(gldouble * v);

void glIndexs(glshort v1);
void glIndexsv(glshort * v);
void glIndexi(glint v1);
void glIndexiv(glint * v);
void glIndexub(glubyte v1);
void glIndexubv(glubyte * v);
void glIndexf(glfloat v1);
void glIndexfv(glfloat * v);
void glIndexd(gldouble v1);
void glIndexdv(gldouble * v);

void glRects(glshort v1);
void glRectsv(glshort * v);
void glRecti(glint v1);
void glRectiv(glint * v);
void glRectf(glfloat v1);
void glRectfv(glfloat * v);
void glRectd(gldouble v1);
void glRectdv(gldouble * v);

void glEvalCoord1f(glfloat v1);
void glEvalCoord1fv(glfloat * v);
void glEvalCoord1d(gldouble v1);
void glEvalCoord1dv(gldouble * v);
void glEvalCoord2f(glfloat v1, glfloat v2);
void glEvalCoord2fv(glfloat * v);
void glEvalCoord2d(gldouble v1, gldouble v2);
void glEvalCoord2dv(gldouble * v);


