


#DelegateCount
3

#ExpOtp
CommandQueueTryFinally<integer>#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer

CommandQueueHandleWithoutRes#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	function lambda(e: Exception): boolean

CommandQueueHandleDefaultRes<integer>#0: 2
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	function lambda(e: Exception): boolean

CommandQueueHandleReplaceRes<integer>#0
	CommandQueueHostQuickFunc<integer,SimpleFunc0Container<integer>>#1: function lambda: integer
	function lambda(lst: List<Exception>): integer

#ReqModules
OpenCLABC


