


#DelegateCount
3

#ExpOtp
CommandQueueTryFinally<integer>#0
	CommandQueueHostQuickFunc<integer>#1: function lambda: integer
	CommandQueueHostQuickFunc<integer>#1: function lambda: integer

CommandQueueHandleWithoutRes#0
	CommandQueueHostQuickFunc<integer>#1: function lambda: integer
	function lambda(e: Exception): boolean

CommandQueueHandleDefaultRes<integer>#0: 2
	CommandQueueHostQuickFunc<integer>#1: function lambda: integer
	function lambda(e: Exception): boolean

CommandQueueHandleReplaceRes<integer>#0
	CommandQueueHostQuickFunc<integer>#1: function lambda: integer
	function lambda(lst: List<Exception>): integer

[EventDebug]: 0 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 

#ReqModules
OpenCLABC


