


#ReqModules
OpenCLABC

#ExpOtp
ConstQueue<System.Int32>#0: 2
----------
2 
4 
4 
----------
2 
4 
4 
==============================
CommandQueueHostBackgoundFunc<System.Int32>#0: Int32 <>lambda*()
----------
3 
9 
9 
----------
3 
9 
9 
==============================
CastQueue<System.Object, System.Int32>#0
	CommandQueueHostBackgoundFunc<System.Object>#1: System.Object <>lambda*()
----------
4 
16 
16 
----------
4 
16 
16 
==============================
[EventDebug]: 13 event's created 
[QueueDebug]: 0 queue's created 
[WaitDebug]: 0 wait handler's created 


