


#DelegateCount
5

#ExpOtp
ConstQueue<integer>#0: 2
------------------------------ 
2 
4 
4 
------------------------------ 
2 
4 
5 
============================== 
CommandQueueHostThreadedFunc<integer,SimpleFunc0Container<integer>>#0: function lambda: integer
------------------------------ 
3 
9 
9 
------------------------------ 
3 
9 
10 
============================== 
CastQueue<Object,integer>#0
	CommandQueueHostThreadedFunc<Object,SimpleFunc0Container<Object>>#1: function lambda: Object
------------------------------ 
4 
16 
16 
------------------------------ 
4 
16 
17 
============================== 
[EventDebug]: 13 event's created 
[QueueRes<T>]: 20 
	QueueResValDirect<integer>: 12 
	QueueResValDirect<Object>: 2 
	QueueResValWrap<integer>: 6 

#ReqModules
OpenCLABC


